### PR TITLE
Housing strategy

### PR DESCRIPTION
**Pull request by paulusv**
solved #70 
also updated to new percepts from upcoming environment.

### CODE REVIEW

**Comment by nvanruyven** [comment]
:+1:

**Comment by karimosman** [comment]
:+1: don't forget to rebase!

**Comment by trensen** [comment]
@tygron-virtual-humans/group-virtual-human 
Please don't use `Merge branch 'master' into (...)` to add commits from `master` into a branch.
To remove this commit and rebase with `master`, execute:

```
git fetch origin
git checkout HousingStrategy
git reset --hard origin/HousingStrategy
git reset --hard HEAD~
git rebase origin/master
```

Then, fix the conflicts in `VH.mas2g` and `VH.goal`.

```
git add .
git rebase --continue
```

Fix other conflicts in `VH.goal` :wink:

```
git add .
git rebase --continue
```

...and the rebase is successful!

Now your local version is the correct one, so force push that version to this branch at origin:

```
git push -f origin HousingStrategy
```

and everything is fine again! :grinning:

**Comment by karimosman** [comment]
Thanks! @trensen  This helped a lot!

**Pull request merged**
