### PR TITLE
Add tests

### LINKED ISSUE #42: Start writing tests

### PR DESCRIPTION
**Pull request by karimosman**
Tests are added on this branch. _Don't delete this branch_ resolved #50 and close #42

### CODE REVIEW

**Comment by karimosman** [comment]
resolved #50

**Comment by karimosman** [comment]
close #42

**Comment by royklip** [comment]
:+1:

**Comment by trensen** [comment]
Currently, `Resolved` and `close` won't close the corresponding issues when merging: they should be in the PR's description since the keywords don't work in comments.

**Comment by paulusv** [comment]
eventually not(bel(stakeholder(3, 'Company', 'Company'))). => does not make sense, why couldnt there be a stakeholder(5, housing, duwo), you don't want that.
should be something like  not(bel(stakeholder(X, _, _)), X > 2.

**Comment by paulusv** [comment]
Also missed do in in do init :)

**Comment by karimosman** [comment]
@paulusv  there can't be a number 5, because the number specifies which type of stakeholder it is. So it's defined like this : stakeholder(ID,Type,Name) with ID  is a 0 for manucipality, a 1 for housing and a 2 for company in this scenario.

**Pull request merged**
